language: node_js
node_js:
    - lts/*
install:
    - npm install
script:
    - npm run lint
    - npm run test
deploy:
    provider: heroku
    api_key:
        secure: r8dpEXmXOH0INV3A788iXLfViudBIoq/D7eIYr/D4FzUkewJ5fMokAgrCShxwqFPLMdK4slkvhP44/+/G3iVyJJwZpVhU0mK+bYEEFi74BOF+GNRP0YykkENhaXIlFCjcnmtPSsGosrGfVDbOYBf0SKpt497bdhzZwMekmBI01mNmMVO8BTTwAOMT5ghKd3T0vcoXjILFgKB5RGVkqtuJ+lU+wOrcKBfME98eYy9MfGyu4YQ84Jd1KC9KKwQJUTle5h10yqM4ZlFCoz5dr2g3lP8S3CkV70X4eA+fpSew47ywZWooIPAIYE7MexoJubDbB1aPmum7rWuXEqR7HGWtnJ0PjBA5EnrzsiG1A7V9PQ6qowp+SXwQa3OB2PAY7Eo5xXENoVSo2ASS9f58BouemUZM/UgQcDNRnM9p13KqdEO5JZO3iSDyvyI+RqfM0KEEz5OekjCbKKFOFdBo8IAXRqmTNxm8L+QvBZUHrFrxnk3DcywsZA0NdbGj+XcfSl1zLObEarqfKxmJWM26DI96r/w8rVDGLWqbGk3BA7afCgRNAAbnblSkXi+SjuU8TdRUyz2UuNeJewqjlLmTSyuSqpF9394xvrGd8NPP7+fhnvQBnkJs8EuH8tRaImwRpTx7563b1Upx3ML7MpdIok4LKj4GOTcFSQqTwRPvtvxKSY=
